### ISSUE TITLE
ali.js的一个bug，旧token过期以后，更换新token仍然无法连接的问题，提供一个解决思路

### ISSUE THREAD

**Issue by doyoman** [ddgksf2013/Scripts#2]
![image](https://user-images.githubusercontent.com/63859866/211709467-7d8a4bf3-ce56-4152-8d14-75eff48a5cda.png)
原因是我选中的位置运行起来以后默认是选择环境变量中存储的值，即使是存储也是存储旧的token，如果删除选中的部分或者把password和获取环境变量的值更换一下位置应也能解决。

**Comment by ddgksf2013** [comment]
solved
