### ISSUE TITLE
12306无法自动跳过

### ISSUE THREAD

**Issue by alexlee728** [ddgksf2013/Scripts#3]
之前打开12306，会立马跳过，现在要等待几秒钟

**Comment by alexlee728** [comment]
![AF8BC085-EF5A-4676-9B02-0108F1EF9621](https://user-images.githubusercontent.com/3183748/221179538-a8e769f0-a5ec-4174-ac9b-964e098138f3.png)
![3571EBDC-4034-4B24-BC1A-E5A1A376231B](https://user-images.githubusercontent.com/3183748/221179567-1520a81a-79af-4d0c-8959-1831e207db26.png)
![A8A5E675-3D71-48A8-BD23-363B8442B7DF](https://user-images.githubusercontent.com/3183748/221179570-3d2bcf00-3ae8-4856-8aa6-4153b6760124.png)


请求和返回的数据，返回总是提示placementNo不能为空

**Comment by ddgksf2013** [comment]
https://raw.githubusercontent.com/ddgksf2013/Scripts/83b0ddc623529468617023736c769e912adbc9d0/12306.js

最新版仅适用QX，Surge请使用上面的旧版本

**Comment by alexlee728** [comment]
> https://raw.githubusercontent.com/ddgksf2013/Scripts/83b0ddc623529468617023736c769e912adbc9d0/12306.js
> 
> 最新版仅适用QX，Surge请使用上面的旧版本

旧版本确实可以了，但是和Startup冲突了，是否可以将startup里的12306像知乎这些拿出来
