### ISSUE TITLE
哔哩哔哩-我的页面-稍后再看按钮不显示

### ISSUE THREAD

**Issue by Sliverala** [ddgksf2013/Scripts#5]
哔哩哔哩-我的页面-稍后再看按钮不显示。
应该是该按钮id更新导致。添加新id后按钮可以正常。
![button_miss](https://github.com/ddgksf2013/Scripts/assets/20553512/1747894d-c5b7-4d3c-8e8e-44e84f17ba10)

![new_id](https://github.com/ddgksf2013/Scripts/assets/20553512/82a5a3de-4e52-49d0-8918-226eefa8a442)

![update_js](https://github.com/ddgksf2013/Scripts/assets/20553512/c2aa11d5-df8f-4ad6-8f71-5582e8d3fa9d)

**Comment by ddgksf2013** [comment]
已解决
